# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clusterctl < Formula
  desc "Cluster lifecycle management CLI tool"
  homepage "https://github.com/dotdevlabs/clusterctl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotdevlabs/clusterctl/releases/download/v0.2.0/clusterctl_darwin_amd64.tar.gz"
      sha256 "2aac759c347d30c8a90505b2429d38130ac1f6553e77c370b1ee1ec9374fee88"

      define_method(:install) do
        bin.install "clusterctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotdevlabs/clusterctl/releases/download/v0.2.0/clusterctl_darwin_arm64.tar.gz"
      sha256 "d1f39f478a98ccb60a22301593683623a8ca1298e5c503cef73d0e2c20a08c9f"

      define_method(:install) do
        bin.install "clusterctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/clusterctl/releases/download/v0.2.0/clusterctl_linux_amd64.tar.gz"
      sha256 "83fbdc042b3d6a1feeb6e1ddfe2f601b433456652e0fb45400e77752b658b8bd"
      define_method(:install) do
        bin.install "clusterctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/clusterctl/releases/download/v0.2.0/clusterctl_linux_arm64.tar.gz"
      sha256 "6d930e084e58b01b49cf47ae68a0cda80f0331079aed639ea23ca044d8b9b8fb"
      define_method(:install) do
        bin.install "clusterctl"
      end
    end
  end

  test do
    system "#{bin}/clusterctl", "version"
  end
end
