# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopctl < Formula
  desc "CLI tool for managing the LoopControl platform"
  homepage "https://github.com/dotdevlabs/loopctl"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.5/loopctl_darwin_amd64.tar.gz"
      sha256 "80ed5deac2327002a5bbf7fb8b62cbd5e08a669318565604aa8fb533d456800a"

      define_method(:install) do
        bin.install "loopctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.5/loopctl_darwin_arm64.tar.gz"
      sha256 "c27a1e139084bdda26b02b5f3b0153542e3ac7122b7d0c69e4a3769ed5899de2"

      define_method(:install) do
        bin.install "loopctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.5/loopctl_linux_amd64.tar.gz"
      sha256 "4ef8b90afa2bf47d440056dec665b6d44eabaeec84972e0886ff053d23b57923"
      define_method(:install) do
        bin.install "loopctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.5/loopctl_linux_arm64.tar.gz"
      sha256 "39b146988f8d48b5cefe60dbbfba5969ecbd82168d8442b009b78cff8f225f34"
      define_method(:install) do
        bin.install "loopctl"
      end
    end
  end

  test do
    system "#{bin}/loopctl version"
  end
end
