# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopctl < Formula
  desc "CLI tool for managing the LoopControl platform"
  homepage "https://github.com/dotdevlabs/loopctl"
  version "0.1.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.14/loopctl_darwin_amd64.tar.gz"
      sha256 "b4dcf9ecaf9bf2d3d639ac1c10a8ba8d455b69b5523921a298fe7fcae6048cba"

      define_method(:install) do
        bin.install "loopctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.14/loopctl_darwin_arm64.tar.gz"
      sha256 "13ad0898ba108edea6fe937f2e18d77e87ecf1f35d7779510d92bca08a43a2b6"

      define_method(:install) do
        bin.install "loopctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.14/loopctl_linux_amd64.tar.gz"
      sha256 "2212d83c8774eeefa51ddf3f8f3ade9a9ba9f597555a3d6bbb0f1ad5e8e772e0"
      define_method(:install) do
        bin.install "loopctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotdevlabs/loopctl/releases/download/v0.1.14/loopctl_linux_arm64.tar.gz"
      sha256 "5177295e98c487290bc5d63396ebb6987380022ee217a6a511fdd1bf79bf1829"
      define_method(:install) do
        bin.install "loopctl"
      end
    end
  end

  test do
    system "#{bin}/loopctl version"
  end
end
